name: quantum-gates
channels:
  - defaults
dependencies:
  - python=3.9
  - setuptools
  - pip:
    - numpy
    - qiskit==1.0.2
    - qiskit-aer
    - qiskit-ibm-provider
    - scipy
    - matplotlib
    - pylatexenc
    - opt-einsum
