name: quantum-gates
channels:
  - defaults
dependencies:
  - python=3.9
  - setuptools
  - pip:
    - numpy
    - qiskit==1.2
    - qiskit-aer==0.15.0
    - qiskit-ibm-runtime==0.28.0
    - scipy
    - matplotlib
    - pylatexenc
    - opt-einsum
    - pytest
    - python-dotenv
    - build
